site_name: AWS AI Practitioner Notes
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Amazon Bedrock: amazonbedrock.md
  - Types of CC: typesofCC.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
